# Site settings
name: Tajdid Rahman
email: tajdidrahman@gmail.com
description: "Hi there! My name's Tajdid Rahman, but you can call me Taj. I'll write more later"

baseurl: "/blog"
url: "http://tajdid.me.uk/blog"
permalink: none
paginate: 6
paginate_path: /blog/page/:num

email: tajdidrahman@gmail.com
twitter_username: tajdidr
github_username:  tajdid

# Stylesheets
sass:
  sass_dir: assets/_scss
  style: compressed

# Build settings
markdown: kramdown
permalink: pretty